### PR TITLE
Media: config: attempt to fix artifacts in drm protected content

### PR DESCRIPTION
**Pull request by beakthoven**
This could fix problems with Netflix and insta that use drm protected content

### CODE REVIEW

**Comment by goshawk22** [comment]
I had problems playing video in Instagram and Reddit where the videos wouldn't play. I was building with the SilonT Kernel.
I found the same logs and, like you, proceeded to remove the unsupported codecs. This seemed to fix the problem in Instagram and Reddit, but resulted in jittery playback in YouTube above 480p.
I eventually fixed the issue by adding back the audio codecs and building with the KharaMe Kernel. Videos played fine in YouTube, Instagram and Reddit, even when other kernels were flashed.

**Comment by beakthoven** [comment]
> I had problems playing video in Instagram and Reddit where the videos wouldn't play. I was building with the SilonT Kernel.
> I found the same logs and, like you, proceeded to remove the unsupported codecs. This seemed to fix the problem in Instagram and Reddit, but resulted in jittery playback in YouTube above 480p.
> I eventually fixed the issue by adding back the audio codecs and building with the KharaMe Kernel. Videos played fine in YouTube, Instagram and Reddit, even when other kernels were flashed.

well i know that kharaMe has no issues with codecs but i think removing those unsupported codecs would result in a better compatibility of Kernels across the board giving users more choice on what they want to use.

**Comment by goshawk22** [comment]
> > I had problems playing video in Instagram and Reddit where the videos wouldn't play. I was building with the SilonT Kernel.
> > I found the same logs and, like you, proceeded to remove the unsupported codecs. This seemed to fix the problem in Instagram and Reddit, but resulted in jittery playback in YouTube above 480p.
> > I eventually fixed the issue by adding back the audio codecs and building with the KharaMe Kernel. Videos played fine in YouTube, Instagram and Reddit, even when other kernels were flashed.
> 
> well i know that kharaMe has no issues with codecs but i think removing those unsupported codecs would result in a better compatibility of Kernels across the board giving users more choice on what they want to use.

But, once I compiled with the KharaMe Kernel, the issue was fixed whatever kernel you later flashed, suggesting it was probably something to do with the kernel headers in SilonT.
Anyway, removing these codecs caused more problems with YouTube and other apps which users seem to care more about.

**Comment by beakthoven** [comment]
> > > I had problems playing video in Instagram and Reddit where the videos wouldn't play. I was building with the SilonT Kernel.
> > > I found the same logs and, like you, proceeded to remove the unsupported codecs. This seemed to fix the problem in Instagram and Reddit, but resulted in jittery playback in YouTube above 480p.
> > > I eventually fixed the issue by adding back the audio codecs and building with the KharaMe Kernel. Videos played fine in YouTube, Instagram and Reddit, even when other kernels were flashed.
> > 
> > 
> > well i know that kharaMe has no issues with codecs but i think removing those unsupported codecs would result in a better compatibility of Kernels across the board giving users more choice on what they want to use.
> 
> But, once I compiled with the KharaMe Kernel, the issue was fixed whatever kernel you later flashed, suggesting it was probably something to do with the kernel headers in SilonT.
> Anyway, removing these codecs caused more problems with YouTube and other apps which users seem to care more about.

well till now in my testing i didn't see any problems with Youtube, Insta, etc using silont and KharaMe kernel.... weird

**Comment by goshawk22** [comment]
> > > > I had problems playing video in Instagram and Reddit where the videos wouldn't play. I was building with the SilonT Kernel.
> > > > I found the same logs and, like you, proceeded to remove the unsupported codecs. This seemed to fix the problem in Instagram and Reddit, but resulted in jittery playback in YouTube above 480p.
> > > > I eventually fixed the issue by adding back the audio codecs and building with the KharaMe Kernel. Videos played fine in YouTube, Instagram and Reddit, even when other kernels were flashed.
> > > 
> > > 
> > > well i know that kharaMe has no issues with codecs but i think removing those unsupported codecs would result in a better compatibility of Kernels across the board giving users more choice on what they want to use.
> > 
> > 
> > But, once I compiled with the KharaMe Kernel, the issue was fixed whatever kernel you later flashed, suggesting it was probably something to do with the kernel headers in SilonT.
> > Anyway, removing these codecs caused more problems with YouTube and other apps which users seem to care more about.
> 
> well till now in my testing i didn't see any problems with Youtube, Insta, etc using silont and KharaMe kernel.... weird

Yeah that is weird - what Kernel do you build with?

**Comment by beakthoven** [comment]
> > > > > I had problems playing video in Instagram and Reddit where the videos wouldn't play. I was building with the SilonT Kernel.
> > > > > I found the same logs and, like you, proceeded to remove the unsupported codecs. This seemed to fix the problem in Instagram and Reddit, but resulted in jittery playback in YouTube above 480p.
> > > > > I eventually fixed the issue by adding back the audio codecs and building with the KharaMe Kernel. Videos played fine in YouTube, Instagram and Reddit, even when other kernels were flashed.
> > > > 
> > > > 
> > > > well i know that kharaMe has no issues with codecs but i think removing those unsupported codecs would result in a better compatibility of Kernels across the board giving users more choice on what they want to use.
> > > 
> > > 
> > > But, once I compiled with the KharaMe Kernel, the issue was fixed whatever kernel you later flashed, suggesting it was probably something to do with the kernel headers in SilonT.
> > > Anyway, removing these codecs caused more problems with YouTube and other apps which users seem to care more about.
> > 
> > 
> > well till now in my testing i didn't see any problems with Youtube, Insta, etc using silont and KharaMe kernel.... weird
> 
> Yeah that is weird - what Kernel do you build with?

well i dont own a realme 5 pro or build for it, my friend built and shared to his testers to try and see if they get any problems. In that we didn't see any

**Pull request closed without merging**
